server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: # 在此处配置要绑定的 rabbitMQ 的服务信息
        defaultRabbit: #表示定义的名称，用于 binding 整合
         type: rabbit # 消息组件类型
         environment:
           spring:
             rabbitmq:
               host: localhost
               port: 5672
               username: guest
               password: guest
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称，表示这是消息的生产者
          destination: studyExchange # 表示要使用的 Exchange 名称定义，即在 rabbit 的 exchange 上可以看到这个字符串命名的 exchange
          contentType: application/json
          binder: defaultRabbit #设置要绑定的消息服务的具体设置，就是上面我们定义的 Rabbit 配置

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔，默认30秒
    lease-expiration-duration-in-seconds: 5
    instance-id: send-8801.com # 在信息列表时显示主机名称
    prefer-ip-address: true #访问的路径变为 IP 地址
